- id: speccy
  name: speccy
  entry: speccy lint
  language: node
  types: [yaml]
  args: []
  additional_dependencies: ["speccy"]
  description: Runs speccy lint on yaml specs.
  minimum_pre_commit_version: '1'
