- id: speccy
  name: speccy
  entry: speccy lint
  language: node
  files: "*.{yml, yaml}"
  args: [--rules=default]
  additional_dependencies: ["speccy"]
  description: Runs speccy lint on yaml specs.
  minimum_pre_commit_version: '1'
